//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.03 at 09:15:05 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.paltvlad.com/spring/market/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.paltvlad.market.core.soap.products;
